site_name: multi-repo-docs-versioning
dev_addr: 0.0.0.0:8000

repo_name: 'GitHub'
repo_url: 'https://github.com/multi-repo-docs-versioning/'

docs_dir: 'content'

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  custom_dir: 'theme'
  language: en
  include_sidebar: true
  feature:
    tabs: false
  i18n:
    prev: 'Previous'
    next: 'Next'


extra_css:
  - assets/styles/extra.css # Our custom styles
  - assets/styles/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
  - assets/js/hljs/highlight.pack.js # Download from https://highlightjs.org/download/ and enable YAML, TOML and Dockerfile
  - assets/js/extra.js

plugins:
  - search

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: false # hljs is used instead of pygment for TOML highlighting support
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - markdown_include.include:
      base_path: content/includes/
      encoding: utf-8
  - toc:
      permalink: true

# Page tree
nav:
  - Welcome: index.md
  - Test: test.md
  - Test2: tests/test2.md
  - repo-docs-2: 
        - page-1: repo-docs-2/docs/page1.md
        - page-2: repo-docs-2/docs/page2.md
  - repo-docs-1:
        - page-1: repo-docs-1/docs/page1.md
        - page-2: repo-docs-1/docs/page2.md      
